#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format:check ||
(
  echo 'Aborting commit: Prettier check failed'
  false;
)

npm run lint ||
(
  echo 'Aborting commit: ESLint check failed'
  false;
)

npm run types:check ||
(
  echo 'Aborting commit: Typescript check failed'
  false;
)

npm run test ||
(
  echo 'Aborting commit: Unit tests failed'
  false;
)

npm run build ||
(
  echo 'Aborting commit: Build failed'
  false;
)

echo 'All checks passed - commiting...'